create table if not exists product(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    quantity int,
    id_product_type int,
    id_supplier int,
    price numeric,
    description varchar(200)
);