create table if not exists client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(100),
    phone_number VARCHAR(11),
    address VARCHAR(255)
);